# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'learn_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 600)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        MainWindow.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_name.setGeometry(QtCore.QRect(10, 50, 251, 21))
        self.lbl_name.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.lbl_name.setObjectName("lbl_name")
        self.prbar = QtWidgets.QProgressBar(self.centralwidget)
        self.prbar.setGeometry(QtCore.QRect(10, 480, 221, 23))
        self.prbar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 40, 40);")
        self.prbar.setProperty("value", 0)
        self.prbar.setObjectName("prbar")
        self.lbl_prog = QtWidgets.QLabel(self.centralwidget)
        self.lbl_prog.setGeometry(QtCore.QRect(10, 440, 101, 21))
        self.lbl_prog.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.lbl_prog.setObjectName("lbl_prog")
        self.lbl_learn = QtWidgets.QLabel(self.centralwidget)
        self.lbl_learn.setGeometry(QtCore.QRect(10, 90, 101, 21))
        self.lbl_learn.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.lbl_learn.setObjectName("lbl_learn")
        self.btn_cards = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cards.setGeometry(QtCore.QRect(10, 120, 201, 31))
        self.btn_cards.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_cards.setObjectName("btn_cards")
        self.btn_learbh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_learbh.setGeometry(QtCore.QRect(10, 160, 201, 31))
        self.btn_learbh.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_learbh.setObjectName("btn_learbh")
        self.btn_write = QtWidgets.QPushButton(self.centralwidget)
        self.btn_write.setGeometry(QtCore.QRect(10, 200, 201, 31))
        self.btn_write.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_write.setObjectName("btn_write")
        self.tbl_wdt = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_wdt.setGeometry(QtCore.QRect(300, 10, 541, 501))
        self.tbl_wdt.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(40, 40, 40);\n"
"border-color: rgb(40, 40, 40);")
        self.tbl_wdt.setObjectName("tbl_wdt")
        self.tbl_wdt.setColumnCount(0)
        self.tbl_wdt.setRowCount(0)
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(10, 0, 40, 40))
        self.btn_exit.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(640, 520, 201, 31))
        self.btn_delete.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_delete.setObjectName("btn_delete")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(10, 510, 201, 31))
        self.btn_reset.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_reset.setObjectName("btn_reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EzLearn - Учите и Запоминайте"))
        self.lbl_name.setText(_translate("MainWindow", "Название"))
        self.lbl_prog.setText(_translate("MainWindow", "Прогресс"))
        self.lbl_learn.setText(_translate("MainWindow", "Изучать"))
        self.btn_cards.setText(_translate("MainWindow", "Карточки"))
        self.btn_learbh.setText(_translate("MainWindow", "Заучивание"))
        self.btn_write.setText(_translate("MainWindow", "Письмо"))
        self.btn_exit.setText(_translate("MainWindow", "🠔"))
        self.btn_delete.setText(_translate("MainWindow", "Удалить"))
        self.btn_reset.setText(_translate("MainWindow", "Сбросить прогресс"))
