# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/young_cucumber/Desktop/help/learn_cards.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(30, 10, 40, 40))
        self.btn_exit.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_exit.setObjectName("btn_exit")
        self.ledit_all = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_all.setGeometry(QtCore.QRect(260, 500, 51, 41))
        self.ledit_all.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.ledit_all.setText("")
        self.ledit_all.setReadOnly(True)
        self.ledit_all.setObjectName("ledit_all")
        self.btn_word_def = QtWidgets.QPushButton(self.centralwidget)
        self.btn_word_def.setGeometry(QtCore.QRect(100, 80, 601, 291))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_word_def.setFont(font)
        self.btn_word_def.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_word_def.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(248, 181, 5);")
        self.btn_word_def.setObjectName("btn_word_def")
        self.lbl_descr = QtWidgets.QLabel(self.centralwidget)
        self.lbl_descr.setGeometry(QtCore.QRect(230, 390, 341, 21))
        self.lbl_descr.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.lbl_descr.setObjectName("lbl_descr")
        self.btn_learn_more = QtWidgets.QPushButton(self.centralwidget)
        self.btn_learn_more.setGeometry(QtCore.QRect(10, 150, 75, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_learn_more.setFont(font)
        self.btn_learn_more.setStyleSheet("background-color: rgba(255, 0, 0, 100);")
        self.btn_learn_more.setObjectName("btn_learn_more")
        self.btn_know = QtWidgets.QPushButton(self.centralwidget)
        self.btn_know.setGeometry(QtCore.QRect(710, 150, 75, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_know.setFont(font)
        self.btn_know.setStyleSheet("background-color: rgba(0, 255, 0, 100);")
        self.btn_know.setObjectName("btn_know")
        self.lbl_all = QtWidgets.QLabel(self.centralwidget)
        self.lbl_all.setGeometry(QtCore.QRect(160, 510, 91, 21))
        self.lbl_all.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.lbl_all.setObjectName("lbl_all")
        self.lbl_know = QtWidgets.QLabel(self.centralwidget)
        self.lbl_know.setGeometry(QtCore.QRect(340, 510, 91, 21))
        self.lbl_know.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.lbl_know.setObjectName("lbl_know")
        self.ledit_know = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_know.setGeometry(QtCore.QRect(440, 500, 51, 41))
        self.ledit_know.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.ledit_know.setText("")
        self.ledit_know.setReadOnly(True)
        self.ledit_know.setObjectName("ledit_know")
        self.lbl_left = QtWidgets.QLabel(self.centralwidget)
        self.lbl_left.setGeometry(QtCore.QRect(520, 510, 91, 21))
        self.lbl_left.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.lbl_left.setObjectName("lbl_left")
        self.ledit_left = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_left.setGeometry(QtCore.QRect(620, 500, 51, 41))
        self.ledit_left.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.ledit_left.setText("")
        self.ledit_left.setReadOnly(True)
        self.ledit_left.setObjectName("ledit_left")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EzLearn - Учите и Запоминайте"))
        self.btn_exit.setText(_translate("MainWindow", "🠔"))
        self.ledit_all.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_word_def.setText(_translate("MainWindow", "Здесь будет слово"))
        self.lbl_descr.setText(_translate("MainWindow", "Нажмите на карточку, чтобы увидеть обратную сторону"))
        self.btn_learn_more.setText(_translate("MainWindow", "Изучать \n"
" еще"))
        self.btn_know.setText(_translate("MainWindow", "Знаю"))
        self.lbl_all.setText(_translate("MainWindow", "Всего слов:"))
        self.lbl_know.setText(_translate("MainWindow", "Усвоено:"))
        self.ledit_know.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_left.setText(_translate("MainWindow", "Осталось:"))
        self.ledit_left.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
