# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_module.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 590)
        MainWindow.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"gridline-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255)\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_create = QtWidgets.QLabel(self.centralwidget)
        self.lbl_create.setGeometry(QtCore.QRect(70, 10, 301, 21))
        self.lbl_create.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.lbl_create.setObjectName("lbl_create")
        self.ledit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_name.setGeometry(QtCore.QRect(20, 70, 591, 41))
        self.ledit_name.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)")
        self.ledit_name.setText("")
        self.ledit_name.setObjectName("ledit_name")
        self.btn_create = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create.setGeometry(QtCore.QRect(20, 490, 231, 41))
        self.btn_create.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_create.setObjectName("btn_create")
        self.lbl_name_module = QtWidgets.QLabel(self.centralwidget)
        self.lbl_name_module.setGeometry(QtCore.QRect(20, 40, 761, 21))
        self.lbl_name_module.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.lbl_name_module.setObjectName("lbl_name_module")
        self.tbl_wdt = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_wdt.setGeometry(QtCore.QRect(20, 120, 591, 351))
        self.tbl_wdt.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"gridline-color: rgb(40, 40, 40);\n"
"border-color: rgb(40, 40, 40);")
        self.tbl_wdt.setObjectName("tbl_wdt")
        self.tbl_wdt.setColumnCount(0)
        self.tbl_wdt.setRowCount(0)
        self.btn_del = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del.setGeometry(QtCore.QRect(620, 120, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_del.setFont(font)
        self.btn_del.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_del.setObjectName("btn_del")
        self.ledit_del = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_del.setGeometry(QtCore.QRect(750, 120, 41, 41))
        self.ledit_del.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.ledit_del.setText("")
        self.ledit_del.setObjectName("ledit_del")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(620, 170, 131, 41))
        self.btn_add.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_add.setObjectName("btn_add")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(10, 0, 40, 40))
        self.btn_exit.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_exit.setObjectName("btn_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("color: rgb(255, 0, 0);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actio_menu = QtWidgets.QAction(MainWindow)
        self.actio_menu.setObjectName("actio_menu")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EzLearn - Учите и Запоминайте"))
        self.lbl_create.setText(_translate("MainWindow", "Создать новый учебный модуль"))
        self.ledit_name.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_create.setText(_translate("MainWindow", "Сохранить"))
        self.lbl_name_module.setText(_translate("MainWindow", "Введите название, например, \"Английский. Фрукты и овощи\""))
        self.btn_del.setText(_translate("MainWindow", "Удалить картоку \n"
" номер"))
        self.ledit_del.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_add.setText(_translate("MainWindow", "+Добавить \n"
" карточку"))
        self.btn_exit.setText(_translate("MainWindow", "🠔"))
        self.actio_menu.setText(_translate("MainWindow", "Вернуться в главное меню"))
        self.action_exit.setText(_translate("MainWindow", "Выйти из приложения"))
