# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 592)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ledit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_login.setGeometry(QtCore.QRect(470, 210, 251, 41))
        self.ledit_login.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"")
        self.ledit_login.setInputMask("")
        self.ledit_login.setText("")
        self.ledit_login.setClearButtonEnabled(False)
        self.ledit_login.setObjectName("ledit_login")
        self.ledit_pswd = QtWidgets.QLineEdit(self.centralwidget)
        self.ledit_pswd.setGeometry(QtCore.QRect(470, 260, 251, 41))
        self.ledit_pswd.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)")
        self.ledit_pswd.setText("")
        self.ledit_pswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ledit_pswd.setObjectName("ledit_pswd")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(470, 310, 251, 41))
        self.btn_login.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_login.setObjectName("btn_login")
        self.btn_sign_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign_up.setGeometry(QtCore.QRect(470, 360, 251, 41))
        self.btn_sign_up.setStyleSheet("background-color: rgb(242, 180, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)")
        self.btn_sign_up.setObjectName("btn_sign_up")
        self.lbl_logo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logo.setGeometry(QtCore.QRect(70, 240, 311, 81))
        self.lbl_logo.setText("")
        self.lbl_logo.setPixmap(QtGui.QPixmap("../NotCode/Logo.png"))
        self.lbl_logo.setObjectName("lbl_logo")
        self.lbl_auth = QtWidgets.QLabel(self.centralwidget)
        self.lbl_auth.setGeometry(QtCore.QRect(470, 160, 151, 31))
        self.lbl_auth.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"\n"
"")
        self.lbl_auth.setObjectName("lbl_auth")
        self.lbl_user = QtWidgets.QLabel(self.centralwidget)
        self.lbl_user.setGeometry(QtCore.QRect(730, 230, 40, 40))
        self.lbl_user.setText("")
        self.lbl_user.setPixmap(QtGui.QPixmap("../NotCode/User.png"))
        self.lbl_user.setObjectName("lbl_user")
        self.lbl_pswd = QtWidgets.QLabel(self.centralwidget)
        self.lbl_pswd.setGeometry(QtCore.QRect(415, 264, 51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_pswd.setFont(font)
        self.lbl_pswd.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"\n"
"")
        self.lbl_pswd.setObjectName("lbl_pswd")
        self.lbl_login = QtWidgets.QLabel(self.centralwidget)
        self.lbl_login.setGeometry(QtCore.QRect(411, 215, 51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_login.setFont(font)
        self.lbl_login.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)\n"
"\n"
"")
        self.lbl_login.setObjectName("lbl_login")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 26))
        self.menubar.setStyleSheet("color: rgb(255, 255, 255)")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("color: rgb(255, 0, 0)\n"
"")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1_8 = QtWidgets.QAction(MainWindow)
        self.action1_8.setObjectName("action1_8")
        self.action_login = QtWidgets.QAction(MainWindow)
        self.action_login.setObjectName("action_login")
        self.action_pswd = QtWidgets.QAction(MainWindow)
        self.action_pswd.setObjectName("action_pswd")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EzLearn - Учите и Запоминайте"))
        self.ledit_login.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_login.setText(_translate("MainWindow", "Войти"))
        self.btn_sign_up.setText(_translate("MainWindow", "Регистация"))
        self.lbl_auth.setText(_translate("MainWindow", "Авторизация"))
        self.lbl_pswd.setText(_translate("MainWindow", "Пароль"))
        self.lbl_login.setText(_translate("MainWindow", " Логин"))
        self.action1_8.setText(_translate("MainWindow", "1) Длина пароля не менее 8 символов"))
        self.action_login.setText(_translate("MainWindow", "Логин"))
        self.action_pswd.setText(_translate("MainWindow", "Пароль"))
